/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.smartphone;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int ScrollView=0x7f04001c;
        public static final int button1=0x7f04000c;
        public static final int buttonBack=0x7f040016;
        public static final int buttonCommand=0x7f04001a;
        public static final int buttonDetails=0x7f040005;
        public static final int buttonIntervention=0x7f040014;
        public static final int buttonMap=0x7f040003;
        public static final int buttonUpdate=0x7f040004;
        public static final int client=0x7f040002;
        public static final int clientText=0x7f04000d;
        public static final int commandPieceText=0x7f040018;
        public static final int commentEditText=0x7f040013;
        public static final int commentText=0x7f040012;
        public static final int description=0x7f040015;
        public static final int employe=0x7f040001;
        public static final int firstnameText=0x7f040008;
        public static final int fistnameEditText=0x7f040009;
        public static final int heure=0x7f040000;
        public static final int hourEditText=0x7f04000f;
        public static final int hourText=0x7f04000e;
        public static final int lastnameEditText=0x7f04000b;
        public static final int lastnameText=0x7f04000a;
        public static final int layout=0x7f040006;
        public static final int listviewperso=0x7f04001d;
        public static final int mapview=0x7f040017;
        public static final int priceEditText=0x7f040011;
        public static final int priceText=0x7f040010;
        public static final int searchText=0x7f040007;
        public static final int spinner=0x7f04001b;
        public static final int spinnerPiece=0x7f040019;
    }
    public static final class layout {
        public static final int affichageitem=0x7f020000;
        public static final int client=0x7f020001;
        public static final int intervention=0x7f020002;
        public static final int main=0x7f020003;
        public static final int map=0x7f020004;
        public static final int piece=0x7f020005;
        public static final int planning=0x7f020006;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int defaut=0x7f030001;
    }
}
