/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.smartphone;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int ScrollView=0x7f040007;
        public static final int TableLayout=0x7f040008;
        public static final int TableRow01=0x7f040009;
        public static final int TextView01=0x7f04000a;
        public static final int TextView02=0x7f04000b;
        public static final int TextView03=0x7f04000c;
        public static final int button1=0x7f040005;
        public static final int clientText=0x7f040006;
        public static final int firstnameText=0x7f040001;
        public static final int fistnameEditText=0x7f040002;
        public static final int lastnameEditText=0x7f040004;
        public static final int lastnameText=0x7f040003;
        public static final int searchText=0x7f040000;
    }
    public static final class layout {
        public static final int client=0x7f020000;
        public static final int main=0x7f020001;
        public static final int planning=0x7f020002;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
    }
}
